-- Alter Table Example
-- ALTER TABLE `@wpprefix@textdomain_syssettingss` ADD COLUMN `dateautoupdate` int(10) NULL;
-- Create Procedure Example
-- CREATE PROCEDURE `sortorderInc` (IN tblName varchar(50), IN curr_sortorder INT)BEGIN DECLARE done INT DEFAULT FALSE;DECLARE _id, _sortOrder INT;DECLARE _uniqueid VARCHAR(10);DECLARE _NEWEND INT DEFAULT 0;DECLARE cur CURSOR FOR select id, uniqueid, sortOrder from tmptbl_incsortorder;DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;SET @GetCount = CONCAT('SELECT count(*) INTO @_count FROM ', tblName, ' where `sortOrder` >= ', curr_sortorder, ' and isDelete = 0');PREPARE stmt1 FROM @GetCount;EXECUTE stmt1;DEALLOCATE PREPARE stmt1;if (@_count > 0) then SET @CreateView = CONCAT('CREATE OR REPLACE view tmptbl_incsortorder as SELECT id,uniqueid,sortOrder FROM ', tblName, ' where `sortOrder` >= ', curr_sortorder, ' and isDelete = 0 ORDER BY sortOrder DESC');PREPARE stmt2 FROM @CreateView;EXECUTE stmt2;DEALLOCATE PREPARE stmt2;SET _NEWEND = curr_sortorder + @_count;SELECT MIN(SORTORDER), MAX(SORTORDER) INTO @MINVAL, @MAXVAL FROM tmptbl_incsortorder;IF @MINVAL > curr_sortorder AND@MAXVAL > @_count THEN GAPFIX: LOOP IF@MINVAL = curr_sortorder THEN LEAVE GAPFIX;END IF;SET@MINVAL = @MINVAL - 1;CALL sortorderDec(tblName, @MINVAL);END LOOP GAPFIX;PREPARE stmt2 FROM@CreateView;EXECUTE stmt2;DEALLOCATE PREPARE stmt2;END IF;OPEN cur;read_loop: LOOP FETCH cur INTO _id, _uniqueid, _sortOrder;IF done THEN LEAVE read_loop; END IF;IF _NEWEND > _sortOrder THEN SET@UpdateTable = CONCAT('UPDATE ', tblName, ' SET sortOrder = ', _NEWEND, ' WHERE id = ', _id);PREPARE stmt3 FROM@UpdateTable;EXECUTE stmt3;DEALLOCATE PREPARE stmt3;END IF;set _NEWEND = _NEWEND - 1;END LOOP read_loop;CLOSE cur;DROP VIEW tmptbl_incsortorder;end if;END
-- Create Table Example
-- CREATE TABLE IF NOT EXISTS @wpprefix@textdomain_impexpsettings (`id` mediumint(9) NOT NULL AUTO_INCREMENT,`uniqueid` varchar(10) NOT NULL,`impexp_sysset` longtext NULL,`impexp_pricset` longtext NULL,	`sortOrder` int(11) NOT NULL DEFAULT '0',`isActive` int(11) NOT NULL DEFAULT '1',`isDelete` int(11) NOT NULL DEFAULT '0',`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`))
-- 08292016
CREATE TABLE IF NOT EXISTS @wpprefix@textdomain_visitorlog (`id` mediumint(9) NOT NULL AUTO_INCREMENT,`uniqueid` varchar(10) NOT NULL,`ipaddress` varchar(50) NOT NULL,`userlogin` int(11) NOT NULL DEFAULT '0',`byip`  int(11) NOT NULL DEFAULT '0',`bycookie`  int(11) NOT NULL DEFAULT '0',`bylogin` int(11) NOT NULL DEFAULT '0',`copyof` varchar(10) NOT NULL DEFAULT '0',`isActive` int(11) NOT NULL DEFAULT '1',`isDelete` int(11) NOT NULL DEFAULT '0',`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updatedate` timestamp NULL,UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`))
-- 09052016
ALTER TABLE @wpprefix@textdomain_visitorlog ADD COLUMN `sessionid` varchar(50) NULL, ADD COLUMN  `lastsessiondate` timestamp NULL, ADD COLUMN  `cookievalue` varchar(50) NULL, ADD COLUMN  `cookiedate` timestamp NULL ;
-- 09142016
ALTER TABLE @wpprefix@textdomain_visitorlog ADD COLUMN `description` varchar(200) NOT NULL DEFAULT ' ';
ALTER TABLE @wpprefix@textdomain_visitorlog ADD COLUMN `sortOrder` int(11) NOT NULL DEFAULT '0';
ALTER TABLE @wpprefix@textdomain_visitorlog CHANGE  `userlogin`  `userlogin` INT( 11 ) NULL DEFAULT  '0';
ALTER TABLE @wpprefix@textdomain_visitorlog CHANGE  `isActive`  `isActive` INT( 11 ) NULL DEFAULT  '1';
ALTER TABLE @wpprefix@textdomain_visitorlog ADD COLUMN `requestpage` varchar(200) NOT NULL DEFAULT ' ';